### PR TITLE
Support WKWebView and extract web files

### PR DESCRIPTION
**Pull request by alex3165**

### CODE REVIEW

**Comment by TristanWright** [comment]
+1

**Comment by tristaaan** [comment]
+1

**Comment by nabilfreeman** [comment]
Hey guys, sorry - didn't spot this PR.

Support for WKWebView would be great for performance.

I'm gonna try this out and take a closer look at the diffs!

**Comment by tristaaan** [comment]
Another reason for WKWebView is it makes integrating [JS <--> Swift Communication](https://github.com/NSHipster/articles/blob/master/2014-08-24-wkwebkit.md#javascript-︎-swift-communication) easier if you end up needing it.

**Comment by nabilfreeman** [comment]
Live!

**Comment by nabilfreeman** [comment]
nice work :stuck_out_tongue_closed_eyes:

**Pull request merged**
